pipeline {
    agent any
    tools {nodejs "node 16.1.0"}
    stages {
        stage('Build') {
            steps {
            	echo 'Building..'
                dir('ekko-front') {
                    sh 'inner ekko-front pwd'
                    sh 'ls'
                }
            	sh 'outer pwd'
                sh 'ls'
            	sh 'npm --prefix ekko-front run build'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sh 'cp -Rf ./ekko-front/dist/* /data/ekko-web/'
            }
        }
    }
}