pipeline {
    agent any
    tools {nodejs "node 16.1.0"}
    stages {
        stage('Build') {
            steps {
            	echo 'Building..'
            	sh 'pwd'
            	sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sh 'cp -Rf ./dist/* /data/ekko-web/'
            }
        }
    }
}