pipeline {
    agent any

    stages {
    	stage('ShutdownES') {
    		steps {
    			sudo systemctl stop elasticsearch
    		}
    	}
        stage('Build') {
            steps {
            	echo 'Building..'
            	sh 'pwd'
            	sh 'docker ps -a'
                sh 'docker build . -t app/ekko-server -f ekko-server/Dockerfile'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sh 'docker container rm -f ekko-server'
                sh 'docker run -d -e SPRING_PROFILES_ACTIVE=dev -e TZ=Asia/Seoul -p 8310:8310 -v /data/logs/ekko-server:/data/logs/ekko-server --name ekko-server app/ekko-server'
            }
        }
        stage('StartupES') {
    		steps {
    			sudo systemctl start elasticsearch
    		}
    	}
    }
}
