pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
            	echo 'Building..'
            	sh 'pwd'
            	sh 'docker ps -a'
                sh 'docker build . -t app/ekko-server -f ekko-server/Dockerfile'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sh 'docker run -d -e SPRING_PROFILES_ACTIVE=dev -e TZ=Asia/Seoul -p 8310:8310 --name ekko-server app/ekko-server'
            }
        }
    }
}