pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
            	echo 'Building..'
            	sh 'pwd'
            	sh 'docker ps -a'
            	sh 'cd ekko-server'
                sh 'docker build -t app/ekko-server .'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}